packaging_format = 2

id = "simplex"
name = "SimpleX"
description.en = "Messaging platform operating without user identifiers"
description.fr = "Plate-forme de messagerie fonctionnant sans identifiants d'utilisateurs"

version = "5.0.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
website = "https://simplex.chat/"
admindoc = "https://github.com/simplex-chat/simplex-chat/blob/stable/docs/SERVER.md"
code = "https://github.com/simplex-chat/simplex-chat"
cpe = "cpe:2.3:a:simplex:simplex_chat"
fund = "https://opencollective.com/simplex-chat"

[integration]
yunohost = ">= 11.1.18"
architectures = ["amd64","arm64"]
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "150M"
ram.runtime = "50M"

[install]

[resources]

 [resources.sources]
    [resources.sources.main]
    url = "https://github.com/skyuk3000/simplex_ynh/releases/download/5.0.0/smp-server"
    sha256 = "cabc03316c837c6b2b7d07b45fb6bb7f1cb24a14bb7c73eeb1208de431d4ad4f"
    in_subdir = false
    extract   = false
    rename    = "smp-server"

    [resources.ports]
    main.default = 5223
    main.exposed = "TCP"

    [resources.system_user]

    [resources.install_dir]
    dir = "/usr/local/bin/__APP__"

    [resources.permissions]
